drop database if exists personal;
create database personal;
use personal;

create table DEPARTAMENTO(
	ID_DEPARTAMENTO int primary key,
    NOMBRE_DEPARTAMENTO VARCHAR(20)
);

create table EMPLEADO(
	ID_EMPLEADO int primary key,
    DNI VARCHAR(9) UNIQUE,
    NOMBRE VARCHAR(25),
    ID_JEFE INT NOT NULL,
    ID_DEPARTAMENTO INT,
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADO(ID_EMPLEADO)
    );
    
    ALTER TABLE EMPLEADO ADD  HIJOS TINYINT;
    
    INSERT INTO DEPARTAMENTOS VALUES ('1','VENTAS');
    INSERT INTO DEPARTAMENTOS VALUES ('2', 'COMPRAS');
    INSERT INTO DEPARTAMENTOS VALUES ('3','RECURSOS HUMANOS');
	
    INSERT INTO EMPLEADO VALUES ('1', '11111111A', 'JOSE LUIS', NULL, '1','2');
    INSERT INTO EMPLEADO VALUES ('2', '22222222B', 'MARI CARMEN', NULL, '1','10');
    INSERT INTO EMPLEADO VALUES ('3', '33333333C', 'JUAN JOSE', NULL, '2','1');
    INSERT INTO EMPLEADO VALUES ('4', '44444444D', 'MARILUZ', NULL, '2','3');
    INSERT INTO EMPLEADO VALUES ('5', '55555555E', 'ALVARO CANO', NULL, '3','0');
	INSERT INTO EMPLEADO VALUES ('6', '66666666F', 'ESTEBAN CO', NULL, '3','2'); 
    
    ALTER TABLE EMPLEADO ADD FECHAINGRESO DATE;
